workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      groups:
        - expo_credentials
    cache:
      cache_paths:
        - ~/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Configure EAS Project
        script: |
          if [ ! -f ".eas" ] || [ ! -f ".eas/project.json" ]; then
            echo "Initializing EAS project..."
            eas init --id 1bc9fd61-7b88-4161-8f32-c4a3cf77ff92 --yes --no-interactive
          else
            echo "EAS project already configured"
          fi
      - name: Build Android APK
        script: |
          eas build --platform android --profile production --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sagarkum1001@gmail.com
