workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      groups:
        - expo_credentials
    cache:
      cache_paths:
        - ~/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build Android APK
        script: |
          eas build --platform android --profile production --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sagarkum1001@gmail.com
